spring.application.name=herhealth

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/herhealthdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=change-this-to-a-long-random-secret-key-12345